### ISSUE TITLE
No releases to download the image

### ISSUE THREAD

**Issue by zhaodong2013062** [twilio/Wireless_Broadband_IoT_Dev_Kit#2]
The link in the readme to download the custom image leads to the releases page, and there are no releases.

**Comment by rbeiter** [comment]
Hello @zhaodong2013062 - our apologies for the missing link.  This is resolved now and you can find the image here: https://github.com/twilio/Wireless_Broadband_IoT_Dev_Kit/blob/master/RELEASES.md
